# Generated by Django 3.0.7 on 2020-06-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200607_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='popular1.png', upload_to='product'),
        ),
    ]
